stages:
  - build
  - deploy-staging
  - deploy-production

build-job:
  image: node:22-alpine3.19
  stage: build
  cache:
    key:
      files:
        - package-lock.json
      prefix: npm
    paths:
      - hackhackgoose/node_modules/
  script:
    - cd hackhackgoose
    - npm install
    - npm run build
    - cd ..
    - mkdir .public
    - cp -r ./* .public
    - cp -r hackhackgoose/dist .public/hackhackgoose
    - rm -rf public
    - mv .public public
  artifacts:
    paths:
      - public

pages-staging:
  stage: deploy-staging
  environment:
    name: staging
    url: https://freetail-hackers-staginggitlabio.vercel.app/
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - npm install -g vercel
    - vercel deploy --prod --token=$VERCEL_TOKEN --yes public/
    - echo "Deploying to staging..."

  needs:
    - build-job
  only:
    - master

pages:
  image: node:22-alpine3.19
  stage: deploy-production
  environment:
    name: production
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual  # This requires manual approval
  script:
    - echo "Deploying to production..."
  artifacts:
    paths:
      - public
  needs:
    - build-job
    - pages-staging